name: builder-tester

on:
  push:
    # Запускаем билдер при каждом пуше в main:
    branches: ["main"]

jobs:
  build:
    # Собираем:
    runs-on: ubuntu-latest
    container: golang:1.23.4
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    # Вот эту хрень тоже пришлось вклячить из-за ошибки
    # fatal: detected dubious ownership in repository at '/__w/sprint_12_final/sprint_12_final'
    # To add an exception for this directory, call:
	  # git config --global --add safe.directory /__w/sprint_12_final/sprint_12_final
    # error obtaining VCS status: exit status 128
	  # Use -buildvcs=false to disable VCS stamping.
    - name: Prep
      run: go env -w GOFLAGS=-buildvcs=false

    - name: Build
      run: go build -v ./...

  tests:
    # Запускаем тесты и проверяем на наличие ошибок:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...

  tests-race:
    # Запускаем тест на гонку:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Test
      run: go test -race -v ./...
  
  lint:
    # Проверяем код на соответствие стилю и отсутствие логических ошибок
    needs: [tests, tests-race]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      # Задолбался я с этим линтером, постоянно ошибки "Error: /usr/bin/tar: ../../../go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/resolve.go: Cannot open: File exists"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true